# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[profile.dev.package.librocksdb-sys]
    opt-level = 3

[profile.dev.package.rocksdb]
    opt-level = 3

[profile.ci-check]
    inherits = "dev"

[profile.ci-check.package.librocksdb-sys]
    opt-level = 0

[profile.ci-check.package.rocksdb]
    opt-level = 0

[profile.release]
    codegen-units = 1
    lto = "fat"
    panic = "abort"
